name: CI-iOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13-xlarge

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.1.app
    
    - name: Build and Test
      run: xcodebuild test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" ONLY_ACTIVE_ARCH=YES
